[SEM-016]: added molecule component side-panel
Ditmar/OpenScience pull request #100
Opened 2024-06-21 16:26 UTC by rodrigoslucka

Como usuario, quiero ver un componente lateral que liste diferentes tags, para poder acceder fácilmente a diferentes temas o categorías del sitio.

2024-06-21 17:13 UTC, DanX3N0 commented
figma: 
![image](https://github.com/Ditmar/OpenScience/assets/128318543/561c1351-e1b8-4b19-9c3e-87ce27de90c1)
pr:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/b9ac9601-66fe-4608-8dbf-56339cef9cbf)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/e6b023d9-a8b3-4377-91db-23066acba5dd)

the variations primary and secondary are the same

2024-06-21 22:41 UTC, Ditmar requested changes
Nice work please read these coments

2024-06-21 22:41 UTC, Ditmar commented on src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.stories.tsx
> +    variant: 'main',
I think will be better to use default like a variant

2024-06-21 22:41 UTC, Ditmar commented on src/ui/components/molecules/side-panel/panel/SPanel.tsx
> +      <Tags labels={tags} />
Hello, it is my fault for not checking the Tags well, this component should be current as simple links, we will use navigation by # to go through the articles.
I'm thinking of another approach, It is probably it was necessary to implement a pub-sub system to communicate with all entry applications, let me think a little bit, but for a while please modify this component

2024-06-23 14:55 UTC, Ditmar approved these changes

2024-06-23 14:57 UTC, Ditmar requested changes
There are  some errors in the design  
mobile
![image](https://github.com/Ditmar/OpenScience/assets/317151/f1f7606c-b5a5-4f82-9f1a-995808f61600)
Desktop 
![image](https://github.com/Ditmar/OpenScience/assets/317151/83519e2c-c4d5-4316-a906-de5c8ab2cb0a)
In desktop mode the menu are so big

2024-06-27 15:24 UTC, merged