Feature/sem 050
Ditmar/OpenScience pull request #12
Opened 2024-05-31 04:07 UTC by ColqueApazaGualberto

Como usuario quiero ver un label que redireccione a las secciones correspondientes.
Test 1 for SEM-050 Atom Review

2024-06-08 02:17 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/6c4296d0-4060-4006-9324-77b1cb6212e6)

It should be just one component with its respective variations

2024-06-13 05:11 UTC, Ditmar requested changes
read the comments

2024-06-13 05:11 UTC, Ditmar commented on src/ui/components/atoms/label-variables/Variables.tsx
> +  };
I don't see it necessary to create a function to translate the data there are too many different approaches to this more easily.
something like this.
```
const colorClassNames: Record<string, string> = {
  main: 'variables--main',
  secondary: 'variables--secondary',
  default: 'variables--primary'
};
```
and to use 
const className = colorClassNames[colorVariant]

2024-06-13 05:11 UTC, Ditmar commented on src/ui/components/atoms/label-variables/styles.scss
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
please replace this code by the embedded fonts

2024-06-18 14:41 UTC, Ditmar approved these changes

2024-06-18 14:41 UTC, merged