[SEM-049]: footer variables, divider and label (resources/page)
Ditmar/OpenScience pull request #124
Opened 2024-06-23 21:18 UTC by oquendo-rocio

…-049]

2024-06-26 02:59 UTC, DanX3N0 commented
the font is very big, fix this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/bc8c8b3d-8092-4b43-a7bd-3fee34aa539d)

2024-06-30 21:16 UTC, Ditmar requested changes
esta mal 
![image](https://github.com/Ditmar/OpenScience/assets/317151/e1372b75-fb92-4407-990b-02c3ef35b6e4)
en pantalla completa deberia ocupar el 100% de la pantalla 
hay problemas con la prte responsive y no se ve como en el figma

2024-06-30 21:16 UTC, Ditmar requested changes
tiene que revisar lo que se le pide

2024-07-02 15:19 UTC, DanX3N0 commented
pr: 
it's oversizing
![image](https://github.com/Ditmar/OpenScience/assets/128318543/90a0aa1f-2d31-4bdd-8168-a99e32ec28f4)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/208984e4-5be2-432b-8f6f-49d2b2f117f6)
center this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/f4d4a806-1666-4a8e-a210-a77fd42f7f95)
fix this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/6d336820-8733-4676-b4b0-19ffa754651f)

2024-07-03 00:04 UTC, DanX3N0 commented
pr:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/2a599a0f-8fc6-4920-ba71-e4fd8a839697)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/7b3c5ed0-4ee2-47cf-9fa5-f39f00c12f78)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/1e613f70-b5d7-48d0-989f-2cf9e5971dfe)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/5e2a54bd-a7d4-4eaf-8839-7d7d90ab5741)

it's ok

2024-07-03 00:57 UTC, Ditmar approved these changes

2024-07-03 00:57 UTC, merged