[SEM - 027]: Volume (Volume List)
Ditmar/OpenScience pull request #126
Opened 2024-06-25 04:59 UTC by Minjjo

Como usuario, quiero ver un componente que me muestre la información detallada de un volumen, para entender su contenido y fecha de publicación.

2024-06-27 15:31 UTC, Minjjo commented
![image](https://github.com/Ditmar/OpenScience/assets/113062275/72aac5e0-6ff9-43b1-b54c-a7c5f3a55056)

2024-06-28 19:22 UTC, Ditmar requested changes
estop deberia ser una grilla de volumenes

2024-07-01 02:16 UTC, Ditmar requested changes

2024-07-01 02:16 UTC, Ditmar commented on src/ui/components/molecules/volume-list/VolumeList.scss
> +    font-size: 0.8rem;
estos estilos se pueden sacar directamente de las variables globales

2024-07-01 02:16 UTC, Ditmar commented on src/ui/components/molecules/volume-list/VolumeList.scss
> +    font-size: 1rem;
lo mismo aqui

2024-07-01 02:16 UTC, Ditmar commented on src/ui/components/molecules/volume-list/VolumeList.scss
> +    font-size: 1.2rem;
lo mismo aqui

2024-07-01 02:16 UTC, Ditmar commented on src/ui/components/molecules/volume-list/VolumeList.scss
> +    font-size: 1.4rem;
lo mismo

2024-07-02 02:34 UTC, DanX3N0 commented
pr:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/fac09a88-7ff0-4906-a59a-a2888bfcec61)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/bdd00642-ada9-4ac5-a08d-8b5e6dea30e2)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/007c8246-3cdb-4673-959c-4695f392cef2)

isn't a grid of volumes check the ticket and figma

2024-07-07 00:45 UTC, Ditmar requested changes
No this component is not good enough

2024-07-07 00:45 UTC, Ditmar commented on src/ui/components/molecules/list-volumen/ListVolumen.stories.tsx
> +  title: 'ui/components/molecules/ListVolumen',
ok First the name not be listVolumen,  since this is only one component

2024-07-07 00:45 UTC, Ditmar commented on src/ui/components/molecules/list-volumen/types/IProps.ts
> +  children: React.ReactNode;
this component will receive a handler to make the click event

2024-09-10 03:48 UTC, closed without merging