[SEM-210]: Crear rutas para la aplicación Openscience en Astro
Ditmar/OpenScience pull request #142
Opened 2024-06-27 23:39 UTC by Victoria-Jimenez-Martinez

Se necesita crear las siguientes rutas en la aplicación Openscience, desarrollada en Astro, para mejorar la navegación y la estructura del sitio web. Además, se debe incluir el uso de los React componentes article-description y label-recent-articles con información específica en cada ruta.

2024-06-27 23:45 UTC, Victoria-Jimenez-Martinez commented
Tenia dudas, en la parte de la ruta dinamica de los articulos.

2024-06-28 03:20 UTC, Ditmar requested changes
please review the comments

2024-06-28 03:20 UTC, Ditmar commented on src/pages/articles/[id].astro
> +const postRes = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`);
this part of the code is necessary please removed it!

2024-06-28 03:20 UTC, Ditmar commented on src/components/article-description.astro
> +  <p>{text}</p>
ok in this part is necessary to use a react component here you need to show how we can use the components, first of all you need to use the base layout . 
Example 
```
---
import Baselayout from '../../layouts/Layout.astro';
import ArticleTitle from '../../ui/components/atoms/article-title/ArticleTitle';
import ArticleDescription from '../../ui/components/atoms/article-description/ArticleDescription';

const uri = Astro.url.pathname;
---

<Baselayout title="Volumentes">
  <ArticleTitle title={uri} variant="primary" />
  <ArticleDescription article="This is the description of the page" />
</Baselayout>

```
Based in this you need to use these components, please refactor de code

2024-06-28 03:20 UTC, Ditmar commented on src/components/article-description.astro
> +  text: string;
you can pass the data through the props, but finally yo need to use the react component

2024-06-28 18:42 UTC, Ditmar approved these changes
nice work!

2024-06-28 19:14 UTC, Ditmar requested changes
test

2024-06-28 19:14 UTC, Ditmar approved these changes

2024-06-28 22:10 UTC, merged