[SEM - 308]: Refactor, isolar los estilos de los componentes SEM-045 & SEM-046
Ditmar/OpenScience pull request #145
Opened 2024-06-28 17:02 UTC by DanielaAlejandraMamaniSilva

Utilizando el nuevo enfoque para aislar los estilos basados en CSS Modules, refactoriza los componentes SEM-045y SEM-046 y modifica sus estilos. 
 SEM - 045 Boton variable(Facebook/Google) ANTES
![image](https://github.com/Ditmar/OpenScience/assets/102200403/d046beda-390a-49e8-a8a0-24f0871c471b)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/6e7093ce-f925-4ab0-9155-4badd958ad26)
DESPUES 
![image](https://github.com/Ditmar/OpenScience/assets/102200403/2cc319ec-e138-49ee-ba23-9c297fb933c2)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/93f6d1c9-5bea-4a2e-90d0-ff71b2828359)
SEM - 046 INPUT VARIABLE FORMULARIO ANTES
![image](https://github.com/Ditmar/OpenScience/assets/102200403/794640f3-48d8-466a-bae6-e7c569135bdd)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/7c4d4e31-9458-423a-b14f-cb05aace3b2f)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/ece0ced9-710d-4700-9ca7-916f4c012566)
DESPUES
![image](https://github.com/Ditmar/OpenScience/assets/102200403/34d30feb-955c-4fdc-b2eb-61014173cbe2)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/b036cb3e-c681-4838-8aeb-feb250213c1c)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/35eab854-56ea-4d99-9d49-213cbfd0c3dd)
 SEM - 045 Boton variable(Facebook/Google) ANTES
![image](https://github.com/Ditmar/OpenScience/assets/102200403/d046beda-390a-49e8-a8a0-24f0871c471b)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/6e7093ce-f925-4ab0-9155-4badd958ad26)
DESPUES 
![image](https://github.com/Ditmar/OpenScience/assets/102200403/2cc319ec-e138-49ee-ba23-9c297fb933c2)
![image](https://github.com/Ditmar/OpenScience/assets/102200403/93f6d1c9-5bea-4a2e-90d0-ff71b2828359)

2024-06-29 22:11 UTC, Ditmar requested changes
rebase your branches

2024-07-03 03:53 UTC, DanielaAlejandraMamaniSilva commented
branch 308 rebased
![Uploading image.png…]()

2024-07-07 00:51 UTC, Ditmar requested changes
please rebase the pr

2024-07-08 21:04 UTC, Ditmar approved these changes

2024-07-08 21:04 UTC, merged