[SEM-071]: Componente Atómico: Contenedor de Contenido
Ditmar/OpenScience pull request #152
Opened 2024-06-30 05:21 UTC by JorgePachecoCordova

Como desarrollador, necesito crear y probar un contenedor de contenido para el componente de popup siguiendo los principios de diseño atómico. El contenedor debe ser presentado en Storybook y probado usando Vitest para asegurar su funcionalidad.
![Captura de pantalla 2024-06-30 011951](https://github.com/Ditmar/OpenScience/assets/170877031/ace23389-a74c-4880-9639-6b257efbda59)

2024-06-30 20:56 UTC, Ditmar requested changes
read the comments

2024-06-30 20:56 UTC, Ditmar commented on src/ui/components/atoms/content-container/image/container.png
please put this imagen in a separated folder called mock

2024-06-30 20:56 UTC, Ditmar commented on src/ui/components/molecules/network-login/network-login.scss
> +    width: 300px;
use rem instead of px

2024-06-30 20:56 UTC, Ditmar commented on src/ui/components/molecules/network-login/network-login.scss
>      width: 800px;
dont'n use pixeles use rem

2024-07-02 02:29 UTC, DanX3N0 commented
pr: 
![image](https://github.com/Ditmar/OpenScience/assets/128318543/e0c41c9c-6cf1-4473-8cc4-4497d7e1b032)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/ef445866-817f-47bf-9530-8fb18a5faea7)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/4e49a70a-13d2-4a32-8800-277c5990f875)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/a4427e86-8b03-473c-a258-ffb382e32012)

2024-07-02 04:45 UTC, JorgePachecoCordova commented on src/ui/components/atoms/content-container/image/container.png
![Captura de pantalla 2024-07-02 003729](https://github.com/Ditmar/OpenScience/assets/170877031/1e8efc77-8658-45cc-861b-1d86defc21d5)
![Captura de pantalla 2024-07-02 003756](https://github.com/Ditmar/OpenScience/assets/170877031/70253c59-31f4-4d09-8c25-cebeccd8f180)
![Captura de pantalla 2024-07-02 003745](https://github.com/Ditmar/OpenScience/assets/170877031/e05e3556-a1c1-459f-929d-646e1e57b163)

2024-09-10 03:48 UTC, closed without merging