feat: add  Filtrado por año [feature/SEM-015]
Ditmar/OpenScience pull request #158
Opened 2024-07-02 15:15 UTC by MadelenC

Como usuario, quiero ver un listado de años disponibles en una interfaz de filtrado, para poder seleccionar y filtrar la información según el año correspondiente.

2024-07-03 00:08 UTC, DanX3N0 commented
pr:
remove the hover color purple
![image](https://github.com/Ditmar/OpenScience/assets/128318543/98d32318-0c78-41b8-b2e5-3fbed2eb749f)

fix this
![image](https://github.com/Ditmar/OpenScience/assets/128318543/8da86848-696f-4600-8642-a2f8713f18ad)

and this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/5915235f-3f6e-4e86-b38b-715db0b93197)

![image](https://github.com/Ditmar/OpenScience/assets/128318543/9296ab47-9df3-41a4-82a9-9214201f3c8c)

2024-07-03 16:18 UTC, DanX3N0 commented
fix this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/cdb2ff3f-88b1-41d3-8033-4112797dbc6c)

2024-07-03 17:25 UTC, DanX3N0 commented
pr: 
![image](https://github.com/Ditmar/OpenScience/assets/128318543/ba86adf7-d112-438d-a995-e4317fdf7cd6)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/f1fa5bd9-ba5c-4162-af5a-9ed04923053e)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/57b67779-5212-4315-be1d-c1a02b53d8ac)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/9a658106-f5a0-4493-8e8b-7f25cbebefaa)

it's ok

2024-07-07 00:41 UTC, Ditmar requested changes
![image](https://github.com/Ditmar/OpenScience/assets/317151/cc2836fa-2439-4f94-82cf-2de655c38b61)

2024-09-10 03:48 UTC, closed without merging