feature: first commit
Ditmar/OpenScience pull request #159
Opened 2024-07-02 15:35 UTC by JoseIgnacioFernandezMamani

Como usuario quiero una pagina donde se muestre el contenido de manera general.

2024-07-02 16:10 UTC, JoseIgnacioFernandezMamani commented
![image](https://github.com/Ditmar/OpenScience/assets/112204563/7fa9ab77-50dd-45a0-9492-850d5071f97b)

2024-07-03 19:58 UTC, Ditmar requested changes
Ok is fine, good job, but please put this organism into the root astro webpage /

2024-07-07 01:03 UTC, Ditmar requested changes
Que pado con este ticket 
no avanzo

2024-07-07 01:06 UTC, Ditmar approved these changes

2024-07-07 01:06 UTC, merged