[sem-048]:LABEL “ARTICULOS”
Ditmar/OpenScience pull request #27
Opened 2024-06-02 14:37 UTC by giovannicv

Como usuario quiero ver un label indicando artículos.

2024-06-03 01:48 UTC, Ditmar requested changes
review the comments

2024-06-03 01:48 UTC, Ditmar commented on package.json
> +    "prettier": "^3.3.0",
don't change the version of prettier

2024-06-03 01:48 UTC, Ditmar commented on src/ui/components/atoms/label-articulo/Label.stories.tsx
> +  title: 'ui/components/atoms/Label',
use the same name and structure of the path ui/components/atoms/label-articles

2024-06-03 01:48 UTC, Ditmar commented on src/ui/components/atoms/label-articulo/styles.scss
> +    font-family: Montserrat;
Nice please check if the font was correctly embedded in the project if it is not please do it

2024-06-03 01:48 UTC, Ditmar commented on src/ui/components/atoms/label-articulo/styles.scss
> +    font-weight: 800;
this variable should be come from the globals styles

2024-06-07 02:55 UTC, DanX3N0 commented
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/837824eb-cfe5-489b-acea-d7b9fb1ecd63)

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/026d9526-17f7-43cd-8367-a8633abfb543)

![image](https://github.com/Ditmar/OpenScience/assets/128318543/093c295f-e4df-499f-a577-1211d30644c8)

the colors are not the same as the figma.

2024-06-08 02:13 UTC, DanX3N0 commented
check the responsive 
![image](https://github.com/Ditmar/OpenScience/assets/128318543/3e9ced51-f75a-48a3-ace1-caf0cc553bdc)

2024-06-13 16:04 UTC, Ditmar approved these changes

2024-06-13 16:04 UTC, merged