[SEM-061] DESCRIPCION ARTICULO
Ditmar/OpenScience pull request #28
Opened 2024-06-02 17:53 UTC by Then-Crimson

Como usuario quiero que se muestre informacion acerca de un articulo.

2024-06-02 18:13 UTC, Ditmar requested changes

2024-06-02 18:13 UTC, Ditmar commented on package.json
> +    "@storybook/react": "^8.1.3",
please don't use the carret into the version please removed

2024-06-02 18:13 UTC, Ditmar commented on src/ui/components/atoms/article-description/styles.scss
> +    /* word-spacing: $ads-letter-spacing; */
remove this comment

2024-06-06 21:51 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/d90ff927-7006-4e93-abe6-7122a17c28b5)
figma:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/11eb4491-9c51-4736-a425-1657c60dedf0)

not according to figma, check the weight of typography

2024-06-08 01:53 UTC, DanX3N0 commented
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/a9eb8f5c-b306-4d26-8352-24ee09f46044)

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/6e5914b0-9f9e-48ae-b70f-8ed618498a75)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/703cf18c-9a5e-42c7-8baa-93b299989085)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/d11bbc28-882e-4c81-933e-389cd38d6cb4)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/4cd34653-c793-40d9-8f5c-fc68e6e74922)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/fffc784c-d8b7-4360-bd92-b4fb01e88740)

it's according to figma

2024-06-08 16:09 UTC, Ditmar reviewed
Nice work

2024-06-08 16:09 UTC, Ditmar commented on src/ui/components/atoms/article-description/ArticleDescription.test.jsx
> +import { render, screen } from '@testing-library/react';
please change the extension of the file to tsx

2024-06-09 03:04 UTC, Ditmar approved these changes

2024-06-09 03:04 UTC, merged