[SEM-056] TAGS
Ditmar/OpenScience pull request #33
Opened 2024-06-03 03:34 UTC by EdwinMiranda1

Como usuario quiero mostrar diferentes tags en un articulo.

2024-06-03 04:49 UTC, Ditmar requested changes

2024-06-03 04:49 UTC, Ditmar commented on package-lock.json
we are using yarn to install all dependencies, remove this file !

2024-06-03 19:17 UTC, Ditmar requested changes

2024-06-03 19:17 UTC, Ditmar commented on package.json
> -    "yarn": ">=1.22.21 <=1.22.22"
don´t change the version of node

2024-06-06 21:08 UTC, DanX3N0 commented
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/c6d785f2-056c-4a3a-b505-2fe603448501)

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/534fcbc4-3f03-4140-bdb3-e129299a42b9)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/61abb24e-2698-4eb7-8361-c4d1d8ea2613)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/a4d80e60-f587-4469-ae0b-ffdb64c43172)

It's according to figma, good job.

2024-06-07 01:36 UTC, Ditmar approved these changes

2024-06-08 20:12 UTC, merged