[SEM - 058-bis]: LABEL COMPARTIR
Ditmar/OpenScience pull request #35
Opened 2024-06-03 21:22 UTC by rodrigoslucka

Como usuario quiero que se indique claramente donde comienza la seccion de Compartir.

2024-06-03 23:14 UTC, Ditmar requested changes
is falling the responsible  
![image](https://github.com/Ditmar/OpenScience/assets/317151/dd17d288-4d5a-46ba-9c17-d38d6ec350f7)

2024-06-03 23:14 UTC, Ditmar commented on src/ui/components/atoms/label-share/Share.stories.tsx
![image](https://github.com/Ditmar/OpenScience/assets/317151/f112e6a3-7940-400e-bfac-c39457bf7588)
is failing the responsible

2024-06-06 20:39 UTC, DanX3N0 commented
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/c346be57-8339-46de-b2a6-a728df69db99)

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/f1f44ec8-56e7-4f9f-abc6-0056ae5c59c3)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/f2c84a27-836f-417f-a0fd-8cbf3b7e2f45)

not according to figma, go and make corrections according to this:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/73739c72-4278-483e-9fc9-c9d86026948c)

2024-06-06 22:10 UTC, Ditmar approved these changes

2024-06-06 22:10 UTC, merged