Feature/sem-042
Ditmar/OpenScience pull request #39
Opened 2024-06-05 03:09 UTC by crismamani

Added atomic variable label component [SEM-042]

2024-06-05 15:24 UTC, DanX3N0 commented
![image](https://github.com/Ditmar/OpenScience/assets/128318543/b36a6f2a-4d2f-4b21-a4d4-c1d9c13f6054)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/6f0160b1-965d-4f2e-a0eb-d9c8d9652d58)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/4bedddd6-836a-4a79-8bf3-0551639bb46b)

it's according to figma

2024-06-07 03:58 UTC, Ditmar requested changes
read the comments

2024-06-07 03:58 UTC, Ditmar commented on src/ui/components/atoms/label-recent-articles/styles.scss
> +  font-weight: 800;
please use $ads-font-weight-second, variable instead directly 800

2024-06-07 20:18 UTC, Ditmar approved these changes

2024-06-07 20:18 UTC, merged