[SEM-051]:ENLACE VARIABLE(UBICACION / SIGUENOS)
Ditmar/OpenScience pull request #40
Opened 2024-06-05 05:21 UTC by soledad1234567890

Como usuario quiero ver enlaces sobre nuestra ubicacion ademas de poder acceder a nuestra pagina de facebook.

2024-06-05 23:07 UTC, DanX3N0 commented
repair the pipe is failing

2024-06-06 21:20 UTC, DanX3N0 commented
PR: 
![image](https://github.com/Ditmar/OpenScience/assets/128318543/f9162f1a-4d2c-4355-befc-429dd25552c7)

it's not according to figma, It should only be one component and its variations.

2024-06-11 17:36 UTC, Ditmar requested changes
read the comments

2024-06-11 17:36 UTC, Ditmar commented on src/ui/components/atoms/variable-location-follow-us/styles.scss
> +  }
I don't see the responsive media queries

2024-06-11 17:36 UTC, Ditmar commented on src/ui/components/atoms/variable-location-follow-us/mock/img/Rectangle168.png
change this file into assets/images

2024-06-18 23:19 UTC, Ditmar requested changes
lee los comentarios

2024-06-18 23:19 UTC, Ditmar commented on src/ui/components/atoms/variable-location-follow-us/VariableLocationFollowUs.stories.tsx
> +    urlfacebok: 'https://www.facebook.com/tuPaginaDeFacebook',
Cuado se desarrollo un componente como este tienes que pensar en la reutilizacion, este componente no escala estas usando URLfacebook, deberia ser general el atomo. solo crea este atomo 
![image](https://github.com/Ditmar/OpenScience/assets/317151/6e9be3c7-4119-4fa2-9ee1-d59cf5dd4bb7)
Que acepte el icono y setee esos estilos asi solo cambiaras el texto y el icono para crear el otro componente, puede agregar otro atomo para crear el dividir entre ellos | con los estilos que correspondan

2024-06-21 22:31 UTC, Ditmar requested changes
read the comments

2024-06-21 22:31 UTC, Ditmar commented on src/ui/components/atoms/variable-location-follow-us/VariableLocationFollowUs.tsx
> +        dangerouslySetInnerHTML={{ __html: icon ?? '<div></div>' }}
change this approach to the new icon component

2024-06-27 15:28 UTC, closed without merging