Componente variable para el Navbar [SEM-035]
Ditmar/OpenScience pull request #44
Opened 2024-06-05 19:04 UTC by AimeAla23

2024-06-05 23:04 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/16b4543c-cf97-468f-b85a-08d8affdea4e)
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/85c1056b-5f41-490c-9e82-746c75dae436)

fix the position of the label.

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/88b2ce68-6103-4cf6-9a5a-768f9c11046f)
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/3ca85355-4a40-480a-bb84-261a92214a71)

the same here

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/e38c0b86-b875-411a-8ae5-b6bdefc7650d)
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/3e645cda-2b3d-4e84-8611-bf2697a74c29)

2024-06-08 14:29 UTC, Ditmar requested changes
read the comments

2024-06-08 14:29 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +    width: 30%;
this variants have no sense because you don't change anything in the styles

2024-06-08 14:29 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +    width: 30%;
this variants have no sense because you don't change anything in the styles

2024-06-08 14:29 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +    width: 30%;
this variants have no sense because you don't change anything in the styles

2024-06-08 14:29 UTC, Ditmar commented on src/ui/components/atoms/navbar/types/IProps.ts
> +  variant?: string;
you have declared the variable variant here but you don't used no where in your component

2024-06-18 19:36 UTC, Ditmar requested changes

2024-06-18 19:36 UTC, Ditmar commented on src/ui/components/atoms/navbar/Navbar.tsx
> +          dangerouslySetInnerHTML={{ __html: icon ?? '<div></div>' }}
use the new approach to manage the icons

2024-06-21 23:56 UTC, closed without merging