1st commit
Ditmar/OpenScience pull request #48
Opened 2024-06-06 18:18 UTC by JersonEM

add breadcrumb's components:
- [slug].astro
- about.astro
- mockData.js
- Breadcrumbs.test.js
- Breadcrumbs.stories.js
- Breadcrumbs.astro
- ArticlePage.astro
- ArticleInfo.test.js
- ArticleInfo.stories.js
- ArticleInfo.astro
- Article.astro

2024-06-06 19:44 UTC, DanX3N0 commented
repair the pipe is failing

2024-06-11 17:39 UTC, Ditmar requested changes
The components must be made following the structure that was proposed, you can't come and get such nonsense out of nowhere, repeat everything you did, everything is wrong in this pr.

2024-06-11 17:39 UTC, Ditmar commented on src/components/ArticleInfo.astro
> +</style>
the component should be made in react

2024-06-16 03:50 UTC, Ditmar requested changes
The pipe is broken this won't be a review

2024-06-16 14:58 UTC, Ditmar requested changes
![image](https://github.com/Ditmar/OpenScience/assets/317151/c9b838b7-a5b1-42c4-9ff5-23f67efebc73)
No estas siguiendo las directivas y practicas establecidas

2024-06-16 14:59 UTC, Ditmar requested changes

2024-06-16 14:59 UTC, Ditmar commented on src/pages/index.astro
>  <Layout title="Welcome to Astro.">
remove this code

2024-06-16 14:59 UTC, Ditmar commented on package-lock.json
dont' change this code

2024-06-18 15:43 UTC, closed without merging

2024-06-18 15:43 UTC, Ditmar commented
I don't see activity in this pr I will close