[SEM-036] logo
Ditmar/OpenScience pull request #49
Opened 2024-06-06 22:06 UTC by angel148

2024-06-06 23:49 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/fb26267d-eab4-4676-923e-970c76c15992)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/ad364ed0-0c2f-4c90-bd3d-bfce756875a2)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/7a276157-1378-47ac-8cad-d645a33f3e20)

FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/d74bde0b-0ff1-4876-950c-cde748f249b6)

it's according to figma.

2024-06-07 04:06 UTC, Ditmar requested changes

2024-06-07 04:06 UTC, Ditmar commented on src/ui/components/atoms/logo/style.scss
> +  }
ok, I don't see the media queries referring to the responsive design, there exists a difference between deskop and mobile, review the figma

2024-06-07 04:06 UTC, Ditmar commented on src/ui/components/atoms/logo/style.scss
> +  width: 130px;
This measure is bab the correct is 130 - 27 = 103 in mobile and ins desktop is other

2024-06-16 20:32 UTC, Ditmar requested changes
You are dragging  149 commits and changing 126 the rebase fail, I won't review this pr

2024-06-16 20:59 UTC, Ditmar requested changes
bad rebase

2024-06-18 15:42 UTC, closed without merging