[sem-068]: Desarrollo del Componente Icono con Etiqueta [MAMANI ALVARADO, ROLY]
Ditmar/OpenScience pull request #50
Opened 2024-06-06 23:07 UTC by Mamaniroly

Como desarrollador, necesito crear y probar un componente de menú burger siguiendo los principios de diseño atómico. El componente debe ser inicialmente presentado en Storybook con todas sus variantes y probado usando Vitest para asegurar su funcionalidad.

2024-06-06 23:41 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/bca6dd1a-6ea5-4fc6-af39-f100dcf33724)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/9c6abd3a-884e-438c-9ab7-dea30879e308)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/10e14075-456b-4111-ae46-210504cc9387)

FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/e6f7c852-c1e5-461f-afe4-626a8cb5e9ad)

except for the background, it is according to the figma

2024-06-07 04:08 UTC, Ditmar requested changes
remove the background

2024-06-07 15:08 UTC, DanX3N0 commented
PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/3bb49e3c-d7fa-4f3c-ac3e-f76c7b52001b)

dark bg:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/d4f3427b-d328-431d-8127-572633e2c54a)

it's according to figma

2024-06-07 20:15 UTC, Ditmar approved these changes

2024-06-07 20:15 UTC, merged