Correting observations SEM-035
Ditmar/OpenScience pull request #75
Opened 2024-06-16 21:35 UTC by AimeAla23

2024-06-18 15:46 UTC, Ditmar requested changes
read the comments

2024-06-18 15:46 UTC, Ditmar commented on src/ui/components/atoms/navbar/Navbar.tsx
> +        <span
you need to use the new approach to manager the icons

2024-06-22 15:28 UTC, DanX3N0 commented
![image](https://github.com/Ditmar/OpenScience/assets/128318543/92a18fc2-a4e7-4577-98eb-2aa93ae7c332)
remove the background

2024-06-28 03:55 UTC, Ditmar requested changes
Please add a description of the ticket and add some snapshots

2024-06-29 00:51 UTC, Ditmar requested changes
no estas siguiendo las pautas del desarrollo marcadas

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +    width: 10rem;
tienes que hacer uso del response to no puedes poner tus propias media queries

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +  @media (width <= 992px) {
lo mismo aqui

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +  @media (width <= 768px) {
lo mismo aqui

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +  @media (width <= 1200px) {
lo mismo aqui

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +  @media (width <= 992px) {
lo mismo aqui

2024-06-29 00:51 UTC, Ditmar commented on src/ui/components/atoms/navbar/styles.scss
> +  @media (width <= 768px) {
lo mismo aqui

2024-06-29 21:51 UTC, Ditmar approved these changes

2024-06-29 21:53 UTC, merged