[SEM-060] LABEL INFORMACION REFERENCIA
Ditmar/OpenScience pull request #9
Opened 2024-05-30 23:26 UTC by cinthiaastoraiqueh

Como usuario quiero que se muestre informacion acerca de las referencias.

2024-06-06 22:14 UTC, Ditmar requested changes

2024-06-06 22:14 UTC, Ditmar commented on yarn.lock
> +vitest@^1.6.0:
remove the carret

2024-06-06 23:47 UTC, DanX3N0 commented
FIGMA:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/08fa9c61-db72-4c16-9e8f-c8e11a206452)

PR:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/536173c5-a441-409f-b4f5-07f567fe1cb9)

the typography font is Lato.
not according to figma.

2024-06-09 02:31 UTC, Ditmar requested changes
The rebase was done poorly

2024-06-11 13:39 UTC, Ditmar requested changes
read de comments

2024-06-12 01:48 UTC, Ditmar requested changes

2024-06-12 01:48 UTC, Ditmar commented on src/ui/components/atoms/reference-information/Reference.apa.tsx
> +          '/src/ui/components/atoms/reference-information/_mocked/references.json',
no it is not necessary to create a fetch data to consume the fetch

2024-06-12 01:50 UTC, Ditmar requested changes
Read the comments

2024-06-12 01:50 UTC, Ditmar commented on src/ui/components/atoms/reference-information/Reference.apa.tsx
> +        // Aquí puedes manejar el error de una manera apropiada, como mostrarlo en la UI
remove all this shit IA-generated code

2024-06-13 16:01 UTC, Ditmar requested changes
Please review the design is not according 
![image](https://github.com/Ditmar/OpenScience/assets/317151/c0411d10-d2ff-4a99-b918-a30b53e64774)

2024-06-14 15:32 UTC, Ditmar requested changes
Este ticket se encuentra mucho tiempo sin salir, si necesta ayuda contacteme por wapp 
![image](https://github.com/Ditmar/OpenScience/assets/317151/8e6a0d20-aa0f-4a4b-9902-dcaae3180a70)
sigue teniendo diferencias con el figma

2024-06-15 15:26 UTC, Ditmar approved these changes

2024-06-15 18:48 UTC, merged