[SEM-038]: Lupa
Ditmar/OpenScience pull request #95
Opened 2024-06-21 00:44 UTC by JOSELEOND

Como usuario de la aplicación web, quiero un componente de búsqueda que contenga un botón con un icono de lupa y que al hacer clic en dicho botón se despliegue un campo de búsqueda.

2024-06-21 17:35 UTC, DanX3N0 commented
pr:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/c42ef07d-c657-4418-b812-afafefd1257c)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/ec3919c8-bc8a-4468-91e2-ba5893cd14e9)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/a111fa7f-3f7b-4946-a2b1-f054ec025278)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/29dc91e0-9c2a-4a29-a8e2-b3b6cb76517c)
moblie :
![image](https://github.com/Ditmar/OpenScience/assets/128318543/1d2028b6-067d-42ff-ad75-7f94e88011ca)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/258f728d-0d50-41d2-9f99-959c489fd154)
![image](https://github.com/Ditmar/OpenScience/assets/128318543/edd10a42-5b68-43aa-aeed-7d4ccb3c7232)

fix the height & width's

2024-06-22 00:03 UTC, Ditmar requested changes
there are  an error in the design

2024-06-22 15:38 UTC, DanX3N0 commented
pr:
![image](https://github.com/Ditmar/OpenScience/assets/128318543/1c26203d-5031-404d-8eae-6a3b5c69730b)

it's ok

2024-06-23 15:14 UTC, Ditmar requested changes
![image](https://github.com/Ditmar/OpenScience/assets/317151/c419579f-c38c-4bf6-8c64-d40c0e4f5b3e)
in mobile it is imposible to see the text !!

2024-06-28 04:25 UTC, JOSELEOND commented
I already fixed it in the mobile view and the rebasing is done

2024-06-29 21:58 UTC, Ditmar requested changes
has que el texto cuando estemos en mobile sea mas grande asi no podemos aprobar esta pr 
![image](https://github.com/Ditmar/OpenScience/assets/317151/1259b5df-ccc5-4e01-8c2e-aa355c875a21)
fijate aqui .
![image](https://github.com/Ditmar/OpenScience/assets/317151/a0e332b2-2f40-4f87-b124-d48ead567e3e)

2024-06-29 22:00 UTC, Ditmar requested changes

2024-07-01 21:13 UTC, Ditmar approved these changes

2024-07-01 21:13 UTC, merged